main_app/urls.py
from django.urls import path
from . import views

# for class based views, use <int:pk> instead of <int:cat_id>
# for function based views, use <int:cat_id> instead of <int:pk>
# pk stands for primary key
# for each route specified, you must have a view function
urlpatterns = [
  # url path for home page & about page
  path('', views.home, name='home'),
  path('about/', views.about, name='about'),
  # url path for trips CRUD
  path('trips/', views.TripIndex.as_view(), name='trips_index'),
  path('trips/<int:pk>/', views.TripDetail.as_view(), name='trips_detail'),
  path('trips/create/', views.TripCreate.as_view(), name='trips_create'),
  path('trips/<int:pk>/update/', views.TripUpdate.as_view(), name='trips_update'),
  path('trips/<int:pk>/delete/', views.TripDelete.as_view(), name='trips_delete'),
  # url path for add checklist, add activity, add photo, assoc destination
  path('add_checklist/<int:trip_id>/', views.add_checklist, name='add_checklist'),
  path('trips/<int:trip_id>/add_activity/', views.add_activity, name='add_activity'),
  # path('trips/<int:trip_id>/add_photo/', views.add_photo, name='add_trip_photo'),
  path('destinations/<int:destination_id>/add_photo/', views.add_photo, name='add_destination_photo'),
  path('destinations/<int:destination_id>/remove_photo/<int:photo_id>', views.remove_photo, name='remove_destination_photo'),
  path('checklist/complete/<int:checklist_id>/', views.mark_complete, name='mark_complete'),

  # path('trips/<int:trip_id>/assoc_destination/<int:destination_id>/', views.assoc_destination, name='assoc_destination'),

  path(
        'trips/<int:trip_id>/assoc_destination/<int:destination_id>/',
        views.assoc_destination,
        name='assoc_destination'
    ),
  path(
        'trips/<int:trip_id>/unassoc_destination/<int:destination_id>/',
        views.unassoc_destination,
        name='unassoc_destination'
    ),
  
  # url path for destinations CRUD
  path('destinations/', views.DestinationIndex.as_view(), name='destinations_index'),
  path('destinations/<int:pk>/', views.DestinationDetail.as_view(), name='destinations_detail'),
  path('destinations/create/', views.DestinationCreate.as_view(), name='destinations_create'),
  path('destinations/<int:pk>/update/', views.DestinationUpdate.as_view(), name='destinations_update'),
  path('destinations/<int:pk>/delete/', views.DestinationDelete.as_view(), name='destinations_delete'),
  # url path for signup
  path('accounts/signup/', views.signup, name='signup'),
  # url path for invitations
  path('trips/<int:trip_id>/invite_users/', views.invite_users, name='invite_users'), 
]

wanderlust/main_app/urls.py
from django.urls import path
from . import views

# for class based views, use <int:pk> instead of <int:cat_id>
# for function based views, use <int:cat_id> instead of <int:pk>
# pk stands for primary key
# for each route specified, you must have a view function
urlpatterns = [
  # url path for home page & about page
  path('', views.home, name='home'),
  path('about/', views.about, name='about'),
  # url path for trips CRUD
  path('trips/', views.TripIndex.as_view(), name='trips_index'),
  path('trips/<int:pk>/', views.TripDetail.as_view(), name='trips_detail'),
  path('trips/create/', views.TripCreate.as_view(), name='trips_create'),
  path('trips/<int:pk>/update/', views.TripUpdate.as_view(), name='trips_update'),
  path('trips/<int:pk>/delete/', views.TripDelete.as_view(), name='trips_delete'),
  # url path for add checklist, add activity, add photo, assoc destination
  path('add_checklist/<int:trip_id>/', views.add_checklist, name='add_checklist'),
  path('trips/<int:trip_id>/add_activity/', views.add_activity, name='add_activity'),
  # path('trips/<int:trip_id>/add_photo/', views.add_photo, name='add_trip_photo'),
  path('destinations/<int:destination_id>/add_photo/', views.add_photo, name='add_destination_photo'),
  path('destinations/<int:destination_id>/remove_photo/<int:photo_id>', views.remove_photo, name='remove_destination_photo'),
  path('checklist/complete/<int:checklist_id>/', views.mark_complete, name='mark_complete'),

  # path('trips/<int:trip_id>/assoc_destination/<int:destination_id>/', views.assoc_destination, name='assoc_destination'),

  path(
        'trips/<int:trip_id>/assoc_destination/<int:destination_id>/',
        views.assoc_destination,
        name='assoc_destination'
    ),
  path(
        'trips/<int:trip_id>/unassoc_destination/<int:destination_id>/',
        views.unassoc_destination,
        name='unassoc_destination'
    ),
  
  # url path for destinations CRUD
  path('destinations/', views.DestinationIndex.as_view(), name='destinations_index'),
  path('destinations/<int:pk>/', views.DestinationDetail.as_view(), name='destinations_detail'),
  path('destinations/create/', views.DestinationCreate.as_view(), name='destinations_create'),
  path('destinations/<int:pk>/update/', views.DestinationUpdate.as_view(), name='destinations_update'),
  path('destinations/<int:pk>/delete/', views.DestinationDelete.as_view(), name='destinations_delete'),
  # url path for signup
  path('accounts/signup/', views.signup, name='signup'),
  # testing
  path('trips/<int:trip_id>/add_destinations/', views.assoc_destination, name='add_destinations'),

]

wanderlust/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date
from django.contrib.auth.models import User


# Create your models here.
class Destinations(models.Model):
    name = models.CharField(max_length=250)
    country = models.CharField(max_length=60)
    language = models.CharField(max_length=100)
    currency = models.CharField(max_length=3)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('destinations_detail', kwargs={'pk': self.id})
    
class Trips(models.Model):
    name = models.CharField(max_length=250)
    startDate = models.DateField(null=True)
    endDate = models.DateField(null=True)
    budget = models.IntegerField(null=True)
    destination_ids = models.ManyToManyField(Destinations, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    accepted_users = models.ManyToManyField(User, related_name='accepted_trips', blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('trips_detail', kwargs={'pk': self.pk})

    class Meta: 
        ordering = ['-startDate']

class TripRequest(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sent_requests')
    receiver = models.ForeignKey(User, on_delete=models.CASCADE, related_name='received_requests')
    trip = models.ForeignKey(Trips, on_delete=models.CASCADE)
    STATUS_CHOICES = (
        ('pending', 'Pending'),
        ('accepted', 'Accepted'),
        ('rejected', 'Rejected'),
    )
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='pending')
    created_at = models.DateTimeField(auto_now_add=True)

class Checklist(models.Model):
    todos = models.CharField(max_length=250)
    complete = models.BooleanField()
    trip = models.ForeignKey(Trips, on_delete=models.CASCADE)

class Travelers(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    trip = models.ForeignKey(Trips, on_delete=models.CASCADE)

class Activities(models.Model):
    plannedAct = models.CharField(max_length=250)
    endDate = models.DateField()
    dueDate = models.DateField()
    trip = models.ForeignKey(Trips, on_delete=models.CASCADE)

class Photos(models.Model):
    url = models.CharField(max_length=200)
    destination_id = models.ForeignKey(Destinations, on_delete=models.CASCADE)

main_app/views.py
from typing import Any, Dict
from operator import itemgetter
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils import timezone
from django.http import JsonResponse

from django.contrib.auth.models import User
from .forms import InvitationForm
from django.utils import timezone


from .models import Trips, Destinations, Photos, Checklist, Travelers, Activities, TripRequest
from .forms import ChecklistForm, ActivityForm, SignupForm, AddDestinationForm
from datetime import datetime
# import these for aws upload
import googlemaps
import requests, json
import uuid # this is to make random numbers
import boto3 # this is to make calls to aws
import os # os.environ['BUCKET_NAME'] is to read environment variables

gmaps = googlemaps.Client(key='AIzaSyCgRAHdFcRKhO-Qszsqpt_fOq4Q7wUMK8Y')

# Views for routes: '/' & '/about/'
def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

# View for routes: Trips CRUD 
class TripIndex(LoginRequiredMixin, ListView):
    model = Trips
    template_name = "main_app/trip_index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        all_trips = Trips.objects.all()

        # Separate upcoming and past trips
        current_date = timezone.now().date()
        upcoming_trips = []
        past_trips = []


 # Get trips created by the user
        user_created_trips = Trips.objects.filter(user=self.request.user)
        
        # Get trips accepted by the user
        accepted_trips = Trips.objects.filter(accepted_users=self.request.user)
        
        # Combine the user's created trips and accepted trips
        user_related_trips = user_created_trips | accepted_trips

        # Get pending invitations for the logged-in user as the receiver
        pending_invitations = TripRequest.objects.filter(receiver=self.request.user, status='pending')




        for trip in user_related_trips:
            days_until = (trip.startDate - current_date).days
            trip.days_until = days_until

            if days_until > 0:
                upcoming_trips.append(trip)
            else:
                past_trips.append(trip)

        # sort trips by start date (asc for upcoming, desc for past)
        upcoming_trips = sorted(upcoming_trips, key=lambda x: x.startDate)
        past_trips = sorted(past_trips, key=lambda x: x.startDate, reverse=True)
    
        context['upcoming_trips'] = upcoming_trips
        context['past_trips'] = past_trips
        context['pending_invitations'] = pending_invitations

        return context


class TripDetail(LoginRequiredMixin, DetailView): 
    model = Trips
    fields = '__all__'
    
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['invitation_form'] = InvitationForm()

         # Get the trip object from the context
        trip = context['object']
        
        # Get all destinations that are not associated with the trip
        not_associated_destinations = Destinations.objects.exclude(id__in=trip.destination_ids.all())
        
        # Get methods from destinations details
        dest_view = DestinationDetail()
        
        # Nearby Places
        nearby_places_by_destination = {}
        # Loop through each destination in the trip
        # Get the lat and long for each destination
        # Then get the nearby places for each destination
        for destination in trip.destination_ids.all():
            name = destination.name
            country = destination.country
            lat, long = dest_view.get_location_details(name, country)
            nearby_places = dest_view.get_nearby_places(lat, long)
            # sort places by rating
            sorted_nearby_places = sorted(nearby_places, key=lambda x: (x.get('user_ratings_total',0),x.get('rating',0)), reverse=True)
            # Add the nearby places to the nearby_places_by_destination dictionary
            nearby_places_by_destination[destination] = sorted_nearby_places
            
        # Pass the nearby places by destination to the template context
        context['nearby_places_by_destination'] = nearby_places_by_destination
        
        # Pass the not_associated_destinations queryset to the template context
        context['not_associated_destinations'] = not_associated_destinations

        context['users'] = User.objects.all()
        
        # Pass the associated destinations to the template context
        context['associated_destinations'] = trip.destination_ids.all()

        # Passing checklist form
        context['checklist_form'] = ChecklistForm()

        trip = context['object']
        context['checklists'] = Checklist.objects.filter(trip_id=trip)
        
        return context

    
    
class TripCreate(LoginRequiredMixin, CreateView): 
    model = Trips
    fields = ['name', 'startDate', 'endDate', 'budget']
    # this is to associate the user with the trip
    def form_valid(self, form):
        # Assign the logged in user (self.request.user)
        form.instance.user = self.request.user
        # Let the CreateView do its job as usual
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['update'] = False
        return context
    
class TripUpdate(LoginRequiredMixin, UpdateView): 
    model = Trips
    fields = ['name', 'startDate', 'endDate', 'budget']
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['update'] = True
        return context

class TripDelete(LoginRequiredMixin, DeleteView): 
    model = Trips
    success_url = '/trips/'

# View for routes: Destinations CRUD
class DestinationIndex(LoginRequiredMixin, ListView): 
    model = Destinations
    fields = '__all__'
    
class DestinationDetail(LoginRequiredMixin, DetailView): 
    model = Destinations
    fields = '__all__'
    
    def get_location_details(self, name, country):
        locdata = gmaps.geocode(f'{name}, {country}')
        latlong = list(locdata[0]['geometry']['location'].values())
        lat = latlong[0]
        long = latlong[1]
        return lat, long
    
    def get_nearby_places(self, lat, long):
        places = gmaps.places_nearby(location=(lat, long), radius=10000, type=['tourist_attraction','casino','shopping_mall','amusement_park','aquarium','art_gallery','cafe','restaurant','bar','department_store','zoo','landmark','natural_feature'], language='en-US')
        return places['results']
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        name = self.object.name
        country = self.object.country
        lat, long = self.get_location_details(name, country)
        timezone = gmaps.timezone((lat, long))
        context['timezone'] = timezone
        context['results'] = self.get_nearby_places(lat, long)
        return context
    

class DestinationCreate(LoginRequiredMixin, CreateView): 
    model = Destinations
    fields = ['name', 'country', 'language', 'currency']
    
class DestinationUpdate(LoginRequiredMixin, UpdateView): 
    model = Destinations
    fields = ['name', 'country', 'language', 'currency']
    
class DestinationDelete(LoginRequiredMixin, DeleteView): 
    model = Destinations
    success_url = '/destinations/'

# View for routes: add checklist, add activity, add photo, assoc destination, invitations
@login_required
def invite_users(request, trip_id):
    trip = get_object_or_404(Trips, id=trip_id)
    print(trip_id)
    if request.method == 'POST':
        form = InvitationForm(request.POST, instance=trip)
        if form.is_valid():
            accepted_users = form.save()
            accepted_users.trip = trip
            accepted_users.save()
            print(accepted_users)
            print(form.data)
            return redirect('trips_detail', pk=trip_id)
    else:
        form = InvitationForm(instance=trip)
    return render(request, 'main_app/invite_users.html', {'form': form, 'trip': trip, 'trip_id': trip_id})

@login_required
def add_checklist(request, trip_id):
    trip = get_object_or_404(Trips, pk=trip_id)
    print(trip)
    if request.method == 'POST':
        form = ChecklistForm(request.POST)
        print(form.data)
        if form.is_valid():
            checklist = form.save(commit=False)
            checklist.trip = trip  # Assign the trip instance
            checklist.save()
            return redirect('trips_detail', pk=trip_id)

    # If there's a problem with the form or request method
    return redirect('trips_detail', pk=trip_id)

@login_required
def add_activity(request, destination_id):
    form = ActivityForm(request.POST)
    if form.is_valid():
        new_activity = form.save(commit=False)
        new_activity.destination_id = destination_id
        new_activity.save()
    return redirect('trips_detail', pk=destination_id)


@login_required
def assoc_destination(request, trip_id, destination_id):
    trip = get_object_or_404(Trips, id=trip_id)
    destination = get_object_or_404(Destinations, id=destination_id)
    trip.destination_ids.add(destination)
    return redirect('trips_detail', pk=trip_id)

@login_required
def unassoc_destination(request, trip_id, destination_id):
    trip = get_object_or_404(Trips, id=trip_id)
    destination = get_object_or_404(Destinations, id=destination_id)
    trip.destination_ids.remove(destination)
    return redirect('trips_detail', pk=trip_id)

main_app/templates/main_app/assoc_destinations.html
{% extends 'base.html' %}

{% block content %}
<h1>Update Destinations to {{ trip.name }}</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Update</button>
</form>
{% endblock %}

main_app/templates/main_app/destinations_detail.html
{% extends 'base.html' %}


{% block content %}


<div class="row" style="margin-top: 50px;">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ destinations.name }}</span>
        <p>{{ destinations.country }}</p>
        <p>{{ destinations.currency }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'destinations_update' destinations.id %}">Edit</a>
        <a href="{% url 'destinations_delete' destinations.id %}">Delete</a>
      </div>
    </div>
  <!-- Insert photo markup below this comment -->
  {% for photo in destinations.photos_set.all %}
  <div>

  
    <img class="responsive-img" src="{{photo.url}}" style="height: 100px; width: 100px; object-fit: cover; margin-left: 20px;">
    <form action="{% url 'remove_destination_photo' destinations.id photo.id %}">
      <br><br>
      <button type="submit" class="btn">Delete Photo</button>
  </form>
  </div>
  {% empty %}
    <div class="card-panel teal-text center-align">No Photos Uploaded</div>
  {% endfor %}
  <form action="{% url 'add_destination_photo' destinations.id %}" enctype="multipart/form-data" method="POST" class="card-panel">
    {% csrf_token %}
    <input type="file" name="photo-file">
    <br><br>
    <button type="submit" class="btn">Upload Photo</button>
</form>
  </div>
    <iframe
    width="600"
    height="450"
    style="border:0; margin-left: 25px;"
    loading="lazy"
    allowfullscreen
    referrerpolicy="no-referrer-when-downgrade"
    src= 'https://www.google.com/maps/embed/v1/search?key=AIzaSyCgRAHdFcRKhO-Qszsqpt_fOq4Q7wUMK8Y
    &q=tourist+attractions+near+{{destinations.name}}' 
    >

  </iframe>
  <div class="card" style="float: right">
  <div class="card-content" >
    <p>Timezone ID: {{ timezone.timeZoneId }}</p>
    <p>Timezone Name: {{ timezone.timeZoneName }}</p>
</div>
</div>


</div>

{% endblock %}

main_app/templates/main_app/destinations_list.html
{% extends 'base.html' %} {% load static %} {% block content %}

<button style="background-color: #9cc8e1; border: none; margin-top: 50px; padding: 10px 20px; border-radius: 20px; font-weight: bolder;">
  <a href="{% url 'destinations_create' %}">Add a Destination</a>
</button>

<div style="margin-bottom: 30px;">
<h1>Places to go</h1>
<div class="container mt-5" >
  {% if object_list %}
  <div class="row">
    {% for destination in object_list %}
    <div class="col s12 m4">
      <div class="card">
        <div class="card-content">
          {% with first_photo=destination.photos_set.first %} 
            {% if first_photo%}
          <img class="responsive-img" src="{{ first_photo.url }}" style="height: 200px; width: auto;" />
            {% else %}
          <div class="teal-text center-align">
            No Photos
          </div>
            {% endif %} 
          {% endwith %}
          <a href="{% url 'destinations_detail' pk=destination.id %}"
            >{{ destination.name }}</a>
          
          <p>{{ destination.country }}</p>
        </div>
      </div>
    </div>
    {% if forloop.counter|divisibleby:"3" and not forloop.last %}
  </div>
  <div class="row">{% endif %} {% endfor %}</div>
  {% else %}
  <p>
    No destinations yet.
    <a href="{% url 'destinations_create' %}">Create your first destination!</a>
  </p>
  {% endif %}
</div>
</div>
{% endblock %}

main_app/templates/main_app/trips_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<style>
  .checklist {
  list-style-type: none;
  padding-left: 0;
}

.checklist li {
  display: flex;
  align-items: center;
  margin-bottom: 10px;
  position: relative;
  font-size: 16px;
}

.checklist .checkmark {
  width: 24px;
  height: 24px;
  border: 2px solid #ccc;
  border-radius: 50%;
  margin-right: 10px;
}

.checklist li.completed .checkmark {
  background-color: #00cc00; /* Green background for completed items */
  border-color: #00cc00; /* Green border for completed items */
}

.checklist li.completed .checkmark:after {
  content: "\2713"; /* White tick mark */
  font-size: 18px;
  color: white;
  display: block;
  text-align: center;
  line-height: 20px;
}

.checklist li.completed {
  text-decoration: line-through; /* Cross out completed items */
  color: #999; /* Grayed-out color for completed items */
}

.checklist li.checklist-item {
  cursor: pointer;
  transition: background-color 0.3s ease-in-out;
}

.checklist li.checklist-item:hover {
  background-color: #f0f0f0;
}
</style>

<div style="margin-bottom: 80px;">
  <div class="col s6 col-offset-3">
    <div style="display: flex; align-items: center;">
      <div>
        <img src="{% static 'assets/images/hero_img.png' %}" alt="" style="height: 200px; margin-right: 50px;">
      </div>
      <div class="card-content">
        <span class="card-title">{{ object.name }}</span>
        <p>{{ object.startDate }} - {{ object.endDate }}</p>
        
        <div class="card-action">
          <a href="{% url 'trips_update' trips.id %}">Edit</a>
          <a href="{% url 'trips_delete' trips.id %}">Delete</a>
        </div>
      </div>
      
    </div>
  </div>
<div>
  
  <div>
    <h4>You are travelling with</h4>
    {% if users.exists %}
      <div style="display: flex; gap: 20px; align-items: center;">
        {% for user in users %}
          <p style="background-color: #9cc8e1; border-radius: 10px; padding: 2px 10px;">{{ user.username }}</p>
          
        {% endfor %}
        <a href="{% url 'invite_users' trips.id %}">Invite more friends!</a>
      </div>
    {% else %}
      <p>No accepted users for this trip.</p>
    {% endif %}
  </div>
  
</div>
  <div class="trip_content" style="display: flex; justify-content: space-between;">
<div class="destinations_list">
  <!-- Trips Destinations -->
  
  <div>
    <h4>Planned Destinations</h4>
    <div style="display: flex; gap: 20px;">
    {% if associated_destinations %} 
    
      {% for destination in associated_destinations %}
        
          <div>
            <div class="card-content">
              {% with first_photo=destination.photos_set.first %} 
                  {% if first_photo%}
                <img class="responsive-img" src="{{ first_photo.url }}" style="height: 200px; width: 200px;" />
                  {% else %}
                <div class="card-panel teal-text center-align">
                  <img src="assets/images/hero_img.png" alt="">
                </div>
                  {% endif %} 
                {% endwith %}
              <h5 class="card-title"> {{ destination.name }} </h6>
              <span class="card-title"> {{ destination.country }} </span>
            </div>
            <div class="card-action">
              <form
                action="{% url 'unassoc_destination' trip_id=trips.id destination_id=destination.id %}"
                method="POST"
              >
                {% csrf_token %}
                <button type="submit" class="btn">Remove</button>
              </form>
            </div>
          
        </div>
        {% endfor %} 
    {% else %}
    <h5>Add your first destination 😿</h5>
    {% endif %}
    </div>
      
  </div>
    
   
       


  <!-- Destinations not added to trip -->
  <h4>More Destinations related to your trip</h4>
  <div style="display: flex; gap: 25px;">
    
    {% if not_associated_destinations %} 
      {% for destination in not_associated_destinations %}
      <div >
        <div class="card-content">
          {% with first_photo=destination.photos_set.first %} 
              {% if first_photo%}
            <img class="responsive-img" src="{{ first_photo.url }}" style="height: 200px; width: 200px;" />
              {% else %}
            <div class=" teal-text center-align">
              <img src="assets/images/hero_img.png" alt="">
            </div>
              {% endif %} 
            {% endwith %}
          <h5 class="card-title"> {{ destination.name }} </h6>
          <span class="card-title"> {{ destination.country }} </span>
        </div>
        <div class="card-action">
          <form
            action="{% url 'assoc_destination' trip_id=trips.id destination_id=destination.id %}"
            method="POST"
          >
            {% csrf_token %}
            <button type="submit" class="btn">Add</button>
          </form>
        </div>
      
    </div>
    {% endfor %} {% else %}
    <h5>No Available Destinations</h5>
    {% endif %}
  </div>
</div>

<!-- Checklist -->

<div class="todo_checklist">
  <h3>Todo List</h3>
  <form action="{% url 'add_checklist' trip_id=object.pk %}" method="POST">
    {% csrf_token %}
    <!-- Render the inputs -->
    {{ checklist_form.as_p }}
    <input type="submit" class="btn" value="Add Todo">
  </form>
  <ul class="checklist">
    {% for checklist in checklists %}
      <li class="checklist-item{% if checklist.complete %} completed{% endif %}" data-complete="{{ checklist.complete }}">
        <span class="checkmark"></span>
        {{ checklist.todos }}
      </li>
    {% endfor %}
  </ul>
</div>

</div>

  <div>
    <div>
      <h3>Places To Visit</h3>
      {% for destination_name, nearby_places in nearby_places_by_destination.items %}
        <h5>Nearby Places for {{ destination_name }}:</h5>
        <div style="display: flex; flex-wrap: wrap;">
          {% for place in nearby_places|slice:":5" %}
            {% if place.opening_hours.open_now %}
            <div class=" teal-text center-align" style="margin-right: 30px;">
              {% if place.photos %}
              <img src="https://maps.googleapis.com/maps/api/place/photo?maxwidth=400&photoreference={{ place.photos.0.photo_reference }}&key=AIzaSyCgRAHdFcRKhO-Qszsqpt_fOq4Q7wUMK8Y" alt="{{ place.name }}" style="height: 200px;">
              {% endif %}
              <p>{{ place.name }}</p>
                <p>{{ place.vicinity }} </p>
              <p>Rating: {{place.rating|default:"0"}}/5 </p>
              <p>Reviewers: {{place.user_ratings_total|default:"0"}}</p>
              <p>(Open Now)</p>
            </div>
            {% else %}
            <div class="red-text center-align" style="margin-right: 30px;">
              {% if place.photos %}
              <img src="https://maps.googleapis.com/maps/api/place/photo?maxwidth=400&photoreference={{ place.photos.0.photo_reference }}&key=AIzaSyCgRAHdFcRKhO-Qszsqpt_fOq4Q7wUMK8Y" alt="{{ place.name }}" style="height: 200px; width: 200px;">
              {% endif %}
              <p>{{ place.name }}</p>
                <p>{{ place.vicinity }}</p> 
              <p>Rating: {{place.rating|default:"0"}}/5 </p>
              <p>Reviewers: {{place.user_ratings_total|default:"0"}}</p>
              <p>(Closed Now)</p>
            </div>
            {% endif %}
          {% endfor %}
        </div>
      {% endfor %}
    </div>
</div>

<script>
  // Get all checklist items
const checklistItems = document.querySelectorAll('.checklist-item');

// Add click event listener to each checklist item
checklistItems.forEach(item => {
  item.addEventListener('click', () => {
    const isComplete = item.getAttribute('data-complete') === 'true';
    
    // Toggle completion status
    item.setAttribute('data-complete', (!isComplete).toString());
    item.classList.toggle('completed', !isComplete);
  });
});
</script>

{% endblock %}